--liquibase formatted sql

--changeset fhirest:hashchain_config
create table store.hashchain_config (
  id            bigint not null generated by default as identity primary key,
  algorithm     text not null,
  version       text not null,
  sys_status    char(1) not null default 'A'
);
create unique index hashchain_config_udx on store.hashchain_config (sys_status) where sys_status = 'A'; -- allow only one active
--

