--liquibase formatted sql

--changeset fhirest-hashchain:hashchain
create table store.hashchain (
  id               bigint not null generated by default as identity primary key,
  config_id        bigint not null references store.hashchain_config(id),
  previous_hash_id bigint references store.hashchain(id),
  resource_uid     bigint not null,
  hash             text not null
);
create unique index hashchain_resource_udx on store.hashchain (resource_uid);
create unique index hashchain_previous_hash_udx ON store.hashchain (previous_hash_id);
create unique index hashchain_single_root_udx ON store.hashchain ((previous_hash_id IS NULL)) WHERE previous_hash_id IS NULL;
create index idx_hashchain_id ON store.hashchain (id DESC);
--

