cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - /tmp/kefhir
    - .gradle/wrapper
    - .gradle/caches

stages:
- prepare
- build
- test
- release

meta-build-image:
  image: docker:stable
  services:
    - docker:dind
  stage: prepare
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/kodality-public/kefhir/kefhir-builder:latest -f .gitlab-ci-Dockerfile  .
    - docker push $CI_REGISTRY/kodality-public/kefhir/kefhir-builder:latest
  only:
    refs:
      - main
    changes:
      - .gitlab-ci-Dockerfile

build:
  image: openjdk:17.0.2-slim
  stage: build
  artifacts:
    paths:
      - "**/build"
    expire_in: 1 hour
  script:
    - ./gradlew assemble

test:
  image: registry.gitlab.com/kodality-public/kefhir/kefhir-builder:latest
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test
    - kefhir-test-app/run-tests.sh
  artifacts:
    when: always
    name: "Test_Result"
    expire_in: 1 day
    paths:
      - "./kefhir-test-app/test-reports"
    reports:
      junit: '*/build/test-results/test/TEST-*.xml'

release snapshot:
  image: openjdk:17.0.2-slim
  stage: release
  dependencies:
    - build
  script:
    - ./gradlew publish
  only:
    - master

release tag:
  image: openjdk:17.0.2-slim
  stage: release
  dependencies:
    - build
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"
    - ./gradlew publish -Pversion="$APP_VERSION"
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches
