image: registry.gitlab.com/kodality-public/gitlab-ci-builder:latest

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - /tmp/kefhir
    - .gradle/caches

stages:
- build
- test
- release

build:
  stage: build
  artifacts:
    paths:
      - "**/build"
    expire_in: 1 hour
  script:
    - ./gradlew assemble

test:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test
    - kefhir-test-app/run-tests.sh
  artifacts:
    when: always
    name: "Test_Result"
    expire_in: 7 D
    paths:
      - "./kefhir-test-app/test-reports"
    reports:
      junit: '*/build/test-results/test/TEST-*.xml'

release snapshot:
  stage: release
  dependencies:
    - build
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - ./gradlew assemble publish
  only:
    - master

release tag:
  stage: release
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"
    - ./gradlew assemble publish -Pversion="$APP_VERSION"
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches
