image: registry.gitlab.com/kodality-public/gitlab-ci-builder:latest

stages:
- build
- test
- release

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    reports:
      junit: '*/build/test-results/test/TEST-*.xml'

test:
  stage: test
  script:
    - ./gradlew test
    - kefhir-test-app/run-tests.sh
  artifacts:
    when: always
    name: "Test_Result"
    expire_in: 7 D
    paths:
      - "./kefhir-test-app/test-reports"
    reports:
      junit: '*/build/test-results/test/TEST-*.xml'

release snapshot:
  stage: release
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - ./gradlew assemble publish
  only:
    - master

release tag:
  stage: release
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"
    - ./gradlew assemble publish -Pversion="$APP_VERSION"
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches
