micronaut:
  server:
    thread-selection: AUTO
    port: 8181

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5151/kephirdb`}
    username: ${DB_APP_USER:kephir}
    password: ${DB_APP_PASSWORD:kephir}
    maximum.pool.size: ${DB_POOL_SIZE:1}
    driver.class.name: org.postgresql.Driver
  liquibase:
    url: ${DB_URL:`jdbc:postgresql://localhost:5151/kephirdb`}
    username: ${DB_ADMIN_USER:kephir}
    password: ${DB_ADMIN_PASSWORD:kephir}
    maximum.pool.size: 1
    driver.class.name: org.postgresql.Driver
liquibase:
  datasources:
    liquibase:
      enabled: true
      change-log: 'classpath:changelog.xml'
      default-schema: 'public'

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
    sensitive: false

definitions-path: ${DEFINITIONS_PATH:../etc/definitions}
