micronaut:
  server:
    thread-selection: AUTO
    port: ${APP_PORT:8181}

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5151/kefhirdb`}
    username: ${DB_APP_USER:kefhir_app}
    password: ${DB_APP_PASSWORD:test}
    maximum.pool.size: ${DB_POOL_SIZE:1}
    driver.class.name: org.postgresql.Driver
  admin:
    url: ${DB_URL:`jdbc:postgresql://localhost:5151/kefhirdb`}
    username: ${DB_ADMIN_USER:kefhir_admin}
    password: ${DB_ADMIN_PASSWORD:test}
    maximum.pool.size: 1
    driver.class.name: org.postgresql.Driver
liquibase:
  datasources:
    admin:
      enabled: true
      change-log: 'classpath:changelog.xml'
      default-schema: 'public'
      parameters:
        app-username: ${datasources.default.username}

endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
    sensitive: false

## due to this https://chat.fhir.org/#narrow/stream/179166-implementers/topic/composite.20search.20parameters.20in.20R5, some definitions altered manually and uploaded to kodality repository
kefhir.conformance.definitions-url: https://kexus.kodality.com/repository/store-public/kefhir/defs-r5.zip
