name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - name: Build
        run: ./gradlew assemble

      - name: Test
        run: ./gradlew test

      - name: Upload junit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: "*/build/test-results/test/TEST-*.xml"

  newman:
    runs-on: ubuntu-latest
    name: Run Newman
#    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      -  uses: gradle/actions/setup-gradle@v3.1.0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '20'
      - run: npm install -g newman
      - working-directory: fhirest-test-app
        run: ./run-tests.sh

      - uses: actions/upload-artifact@v4
        with:
          name: newman
          path: "./kefhir-test-app/test-reports/*"
