on: [workflow_dispatch,push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - name: Build
        run: ./gradlew build

#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          path: '*/build/libs'

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_USER: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
