name: Code Stats
on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Collect code statistics
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - run: ./etc/collect-logs.sh
      - uses: actions/upload-artifact@v4
        with:
          name: logs.md
          path: "./etc/logs.md"

      - run: ./etc/list-deps.sh
      - uses: actions/upload-artifact@v4
        with:
          name: deps.md
          path: "./etc/deps.md"

      - run: ./gradlew fhirest-test-app:dependencyCheckAnalyze > dependency-check.md
      - uses: actions/upload-artifact@v4
        with:
          name: dependency-check.md
          path: "./dependency-check.md"
