server:
  port: 8181

spring:
  datasource:
    default:
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5151/fhirestdb}
      username: ${DB_APP_USER:fhirest_app}
      password: ${DB_APP_PASSWORD:test}
      maximum-pool-size: ${DB_POOL_SIZE:1}
      driver-class-name: org.postgresql.Driver
    admin:
      jdbc-url: ${spring.datasource.default.jdbc-url}
      username: ${DB_ADMIN_USER:fhirest_admin}
      password: ${DB_ADMIN_PASSWORD:test}
      maximum-pool-size: 1
      driver-class-name: org.postgresql.Driver
      liquibase:
        change-log: 'classpath:changelog.yml'
        parameters:
          app-username: ${spring.datasource.default.username}

#  spring:
#    datasource:
#      hikari:
#        jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5151/fhirestdb}
#        username: ${DB_APP_USER:fhirest_admin}
#        password: ${DB_APP_PASSWORD:test}
#        maximum-pool-size: ${DB_POOL_SIZE:1}
#        driver-class-name: org.postgresql.Driver
#    liquibase:
#      url: ${DB_URL:jdbc:postgresql://localhost:5151/fhirestdb}
#      user: postgres
#      password: postgres
#      change-log: 'classpath:changelog.yml'
#      parameters:
#        app-username: ${spring.datasource.hikari.username}


management:
  endpoints:
    web.exposure.include: health, prometheus, info
    health.show-details: always

## due to this https://chat.fhir.org/#narrow/stream/179166-implementers/topic/composite.20search.20parameters.20in.20R5, some definitions altered manually and uploaded to kodality repository
fhirest.conformance.definitions-url: https://kexus.kodality.com/repository/store-public/kefhir/defs-r5.zip
# fhirest.oauth.jwks-url: https://auth.kodality.dev/realms/terminology/protocol/openid-connect/certs
