server:
  port: 8181

spring:
  datasource:
    default:
      url: ${DB_URL:jdbc:postgresql://localhost:5151/fhirestdb}
      username: ${DB_APP_USER:fhirest_app}
      password: ${DB_APP_PASSWORD:test}
      maxActive: ${DB_POOL_SIZE:1}
      driverClassName: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
    admin:
      url: ${spring.datasource.default.url}
      username: ${DB_ADMIN_USER:fhirest_admin}
      password: ${DB_ADMIN_PASSWORD:test}
      maxActive: 1
      driverClassName: org.postgresql.Driver
      type: org.springframework.jdbc.datasource.SimpleDriverDataSource
      liquibase:
        change-log: 'classpath:changelog.yml'
        parameters:
          app-username: ${spring.datasource.default.username}


management:
  endpoints:
    web.exposure.include: health, prometheus, info
    health.show-details: always

## due to this https://chat.fhir.org/#narrow/stream/179166-implementers/topic/composite.20search.20parameters.20in.20R5, some definitions altered manually and uploaded to kodality repository
fhirest.conformance.definitions-url: https://kexus.kodality.com/repository/store-public/kefhir/defs-r5.zip
